### ISSUE TITLE
[Question] Script example

### ISSUE THREAD

**Issue by hw-monkey** [tomaae/homeassistant-mikrotik_router#136]
I thought I understood how to execute a script, but I guess not. I assumed that I would create an action that would call the script service, and then just call the named script that is saved on Mikrotik. This does not seem to be the case. Do you have an example?

Here is what I am talking about:
```
alias: Sunset +1 hour
description: 'an hour after sunset'
mode: single
trigger:
  - platform: sun
    event: sunset
    offset: '01:00:00'
action:
  - service: mikrotik_router.run_script
    data: usb-on
```

Restult:
`Message malformed: expected dict for dictionary value @ data['action'][0]['data']`

**Comment by hw-monkey** [comment]
Got it. I used the Developer Tools services to get a better understanding of the YAML
```
service: mikrotik_router.run_script
data:
  router: Mikrotik
  script: usb-on
```

**Comment by tomaae** [comment]
Yea, its set up to fill an example in developer tools.

```
run_script:
  description: Run script on Mikrotik
  fields:
    router:
      description: Name of the router
      example: "Mikrotik"
    script:
      description: Name of the script
      example: "MyScript"
```
